language: c
compiler:
  - gcc
  - clang
  - i686-w64-mingw32-gcc

script: ./travis-ci-build.sh

before_install:
  - sudo apt-get update -qq
  - sudo apt-get remove -qq -y mingw32
  - sudo apt-get install -q -y mingw-w64

notifications:
  irc: "irc.freenode.org#spearmint"
  on_success: change
  on_failure: always
